# Generated by Django 2.2.6 on 2019-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty', models.CharField(choices=[['FASILKOM', 'FASILKOM'], ['FK', 'FK'], ['FKG', 'FKG'], ['FT', 'FT'], ['FKM', 'FKM'], ['FARMASI', 'FARMASI'], ['FIK', 'FIK'], ['FMIPA', 'FMIPA'], ['FIB', 'FIB'], ['FISIP', 'FISIP'], ['FIA', 'FIA'], ['FEB', 'FEB'], ['FH', 'FH'], ['PSIKOLOGI', 'PSIKOLOGI'], ['VOKASI', 'VOKASI']], max_length=500)),
                ('Satisfaction', models.IntegerField()),
                ('Comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
