# Generated by Django 2.2.7 on 2019-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quotes',
            field=models.CharField(max_length=500),
        ),
    ]
